# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\UI_DialogStudent.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

from src.components.ListBoxWidget import ListBoxWidget


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(909, 450)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Dialog.sizePolicy().hasHeightForWidth())
        Dialog.setSizePolicy(sizePolicy)
        Dialog.setMinimumSize(QtCore.QSize(773, 450))
        Dialog.setMaximumSize(QtCore.QSize(909, 450))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        Dialog.setFont(font)
        Dialog.setStyleSheet("background: #002A44;\n"
"color: #dedede;")
        Dialog.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Cameroon))
        Dialog.setSizeGripEnabled(True)
        Dialog.setModal(True)
        self.student_name_label_2 = QtWidgets.QLabel(Dialog)
        self.student_name_label_2.setGeometry(QtCore.QRect(260, 20, 401, 38))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_name_label_2.sizePolicy().hasHeightForWidth())
        self.student_name_label_2.setSizePolicy(sizePolicy)
        self.student_name_label_2.setMinimumSize(QtCore.QSize(150, 35))
        self.student_name_label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.student_name_label_2.setFont(font)
        self.student_name_label_2.setStyleSheet("color: #dedede;\n"
"background: transparent;")
        self.student_name_label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.student_name_label_2.setObjectName("student_name_label_2")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 80, 894, 271))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(10)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout()
        self.verticalLayout_11.setContentsMargins(10, -1, -1, -1)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.student_name_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_name_label.sizePolicy().hasHeightForWidth())
        self.student_name_label.setSizePolicy(sizePolicy)
        self.student_name_label.setMinimumSize(QtCore.QSize(150, 35))
        self.student_name_label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.student_name_label.setFont(font)
        self.student_name_label.setStyleSheet("color: #dedede;\n"
"background: transparent;")
        self.student_name_label.setObjectName("student_name_label")
        self.horizontalLayout_6.addWidget(self.student_name_label)
        self.student_name_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_name_lineEdit.sizePolicy().hasHeightForWidth())
        self.student_name_lineEdit.setSizePolicy(sizePolicy)
        self.student_name_lineEdit.setMinimumSize(QtCore.QSize(250, 35))
        self.student_name_lineEdit.setMaximumSize(QtCore.QSize(250, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.student_name_lineEdit.setFont(font)
        self.student_name_lineEdit.setStyleSheet("QLineEdit {\n"
"    padding: 0 15px 0 27px;\n"
"    border: 2px solid #dedede;\n"
"    color: #dedede;\n"
"    background: transparent;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QLineEdit:focus, QLineEdit:hover  {\n"
"    border-color: #F38533;\n"
"}")
        self.student_name_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.student_name_lineEdit.setObjectName("student_name_lineEdit")
        self.horizontalLayout_6.addWidget(self.student_name_lineEdit)
        self.horizontalLayout_6.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.student_surname_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_surname_label.sizePolicy().hasHeightForWidth())
        self.student_surname_label.setSizePolicy(sizePolicy)
        self.student_surname_label.setMinimumSize(QtCore.QSize(150, 35))
        self.student_surname_label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.student_surname_label.setFont(font)
        self.student_surname_label.setStyleSheet("color: #dedede;\n"
"background: transparent;")
        self.student_surname_label.setObjectName("student_surname_label")
        self.horizontalLayout_7.addWidget(self.student_surname_label)
        self.student_surname_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_surname_lineEdit.sizePolicy().hasHeightForWidth())
        self.student_surname_lineEdit.setSizePolicy(sizePolicy)
        self.student_surname_lineEdit.setMinimumSize(QtCore.QSize(250, 35))
        self.student_surname_lineEdit.setMaximumSize(QtCore.QSize(250, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.student_surname_lineEdit.setFont(font)
        self.student_surname_lineEdit.setStyleSheet("QLineEdit {\n"
"    padding: 0 15px 0 27px;\n"
"    border: 2px solid #dedede;\n"
"    color: #dedede;\n"
"    background: transparent;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QLineEdit:focus, QLineEdit:hover  {\n"
"    border-color: #F38533;\n"
"}")
        self.student_surname_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.student_surname_lineEdit.setObjectName("student_surname_lineEdit")
        self.horizontalLayout_7.addWidget(self.student_surname_lineEdit)
        self.horizontalLayout_7.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.student_register_number_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_register_number_label.sizePolicy().hasHeightForWidth())
        self.student_register_number_label.setSizePolicy(sizePolicy)
        self.student_register_number_label.setMinimumSize(QtCore.QSize(150, 35))
        self.student_register_number_label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.student_register_number_label.setFont(font)
        self.student_register_number_label.setStyleSheet("color: #dedede;\n"
"background: transparent;")
        self.student_register_number_label.setObjectName("student_register_number_label")
        self.horizontalLayout_8.addWidget(self.student_register_number_label)
        self.student_register_number_lineEdit = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_register_number_lineEdit.sizePolicy().hasHeightForWidth())
        self.student_register_number_lineEdit.setSizePolicy(sizePolicy)
        self.student_register_number_lineEdit.setMinimumSize(QtCore.QSize(250, 35))
        self.student_register_number_lineEdit.setMaximumSize(QtCore.QSize(250, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.student_register_number_lineEdit.setFont(font)
        self.student_register_number_lineEdit.setStyleSheet("QLineEdit {\n"
"    padding: 0 15px 0 27px;\n"
"    border: 2px solid #dedede;\n"
"    color: #dedede;\n"
"    background: transparent;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QLineEdit:focus, QLineEdit:hover  {\n"
"    border-color: #F38533;\n"
"}")
        self.student_register_number_lineEdit.setAlignment(QtCore.Qt.AlignCenter)
        self.student_register_number_lineEdit.setObjectName("student_register_number_lineEdit")
        self.horizontalLayout_8.addWidget(self.student_register_number_lineEdit)
        self.horizontalLayout_8.setStretch(1, 1)
        self.verticalLayout_11.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.student_level_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_level_label.sizePolicy().hasHeightForWidth())
        self.student_level_label.setSizePolicy(sizePolicy)
        self.student_level_label.setMinimumSize(QtCore.QSize(150, 35))
        self.student_level_label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.student_level_label.setFont(font)
        self.student_level_label.setStyleSheet("color: #dedede;\n"
"background: transparent;")
        self.student_level_label.setObjectName("student_level_label")
        self.horizontalLayout_9.addWidget(self.student_level_label)
        self.student_level_spinBox = QtWidgets.QSpinBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_level_spinBox.sizePolicy().hasHeightForWidth())
        self.student_level_spinBox.setSizePolicy(sizePolicy)
        self.student_level_spinBox.setMinimumSize(QtCore.QSize(250, 35))
        self.student_level_spinBox.setMaximumSize(QtCore.QSize(16777215, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.student_level_spinBox.setFont(font)
        self.student_level_spinBox.setStyleSheet("QSpinBox {\n"
"    padding: 0 15px 0 27px;\n"
"    border: 2px solid #dedede;\n"
"    color: #dedede;\n"
"    background: transparent;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QSpinBox:hover, QSpinBox:focus {\n"
"    border-color: #F38533;\n"
"}")
        self.student_level_spinBox.setMinimum(1)
        self.student_level_spinBox.setMaximum(5)
        self.student_level_spinBox.setObjectName("student_level_spinBox")
        self.horizontalLayout_9.addWidget(self.student_level_spinBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.student_discipline_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_discipline_label.sizePolicy().hasHeightForWidth())
        self.student_discipline_label.setSizePolicy(sizePolicy)
        self.student_discipline_label.setMinimumSize(QtCore.QSize(150, 35))
        self.student_discipline_label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.student_discipline_label.setFont(font)
        self.student_discipline_label.setStyleSheet("color: #dedede;\n"
"background: transparent;")
        self.student_discipline_label.setObjectName("student_discipline_label")
        self.horizontalLayout_10.addWidget(self.student_discipline_label)
        self.student_discipline_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_discipline_comboBox.sizePolicy().hasHeightForWidth())
        self.student_discipline_comboBox.setSizePolicy(sizePolicy)
        self.student_discipline_comboBox.setMinimumSize(QtCore.QSize(250, 35))
        self.student_discipline_comboBox.setMaximumSize(QtCore.QSize(250, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.student_discipline_comboBox.setFont(font)
        self.student_discipline_comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.student_discipline_comboBox.setStyleSheet("QComboBox {\n"
"    padding: 0 15px 0 27px;\n"
"    border: 2px solid #dedede;\n"
"    color: #dedede;\n"
"    background: transparent;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: #dedede;\n"
"    padding: 10px;\n"
"    selection-background-color: #F38533;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #F38533;\n"
"}\n"
"\n"
"")
        self.student_discipline_comboBox.setObjectName("student_discipline_comboBox")
        self.student_discipline_comboBox.addItem("")
        self.student_discipline_comboBox.addItem("")
        self.student_discipline_comboBox.addItem("")
        self.student_discipline_comboBox.addItem("")
        self.student_discipline_comboBox.addItem("")
        self.student_discipline_comboBox.addItem("")
        self.student_discipline_comboBox.addItem("")
        self.student_discipline_comboBox.addItem("")
        self.horizontalLayout_10.addWidget(self.student_discipline_comboBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.student_axe_label = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_axe_label.sizePolicy().hasHeightForWidth())
        self.student_axe_label.setSizePolicy(sizePolicy)
        self.student_axe_label.setMinimumSize(QtCore.QSize(150, 35))
        self.student_axe_label.setMaximumSize(QtCore.QSize(150, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.student_axe_label.setFont(font)
        self.student_axe_label.setStyleSheet("color: #dedede;\n"
"background: transparent;")
        self.student_axe_label.setObjectName("student_axe_label")
        self.horizontalLayout_11.addWidget(self.student_axe_label)
        self.student_axe_comboBox = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.student_axe_comboBox.sizePolicy().hasHeightForWidth())
        self.student_axe_comboBox.setSizePolicy(sizePolicy)
        self.student_axe_comboBox.setMinimumSize(QtCore.QSize(250, 35))
        self.student_axe_comboBox.setMaximumSize(QtCore.QSize(250, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.student_axe_comboBox.setFont(font)
        self.student_axe_comboBox.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.student_axe_comboBox.setStyleSheet("QComboBox {\n"
"    padding: 0 15px 0 27px;\n"
"    border: 2px solid #dedede;\n"
"    color: #dedede;\n"
"    background: transparent;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView {\n"
"    color: #dedede;\n"
"    padding: 10px;\n"
"    selection-background-color: #F38533;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #F38533;\n"
"}\n"
"\n"
"")
        self.student_axe_comboBox.setObjectName("student_axe_comboBox")
        self.horizontalLayout_11.addWidget(self.student_axe_comboBox)
        self.verticalLayout_11.addLayout(self.horizontalLayout_11)
        self.horizontalLayout.addLayout(self.verticalLayout_11)
        self.verticalLayout_13 = QtWidgets.QVBoxLayout()
        self.verticalLayout_13.setContentsMargins(-1, -1, 10, -1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout()
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_drag_and_drop = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_drag_and_drop.sizePolicy().hasHeightForWidth())
        self.label_drag_and_drop.setSizePolicy(sizePolicy)
        self.label_drag_and_drop.setMinimumSize(QtCore.QSize(150, 35))
        self.label_drag_and_drop.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_drag_and_drop.setFont(font)
        self.label_drag_and_drop.setStyleSheet("color: #dedede;\n"
"background: transparent;")
        self.label_drag_and_drop.setAlignment(QtCore.Qt.AlignCenter)
        self.label_drag_and_drop.setObjectName("label_drag_and_drop")
        self.verticalLayout_12.addWidget(self.label_drag_and_drop, 0, QtCore.Qt.AlignTop)
        self.drag_and_drop_box = ListBoxWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.drag_and_drop_box.sizePolicy().hasHeightForWidth())
        self.drag_and_drop_box.setSizePolicy(sizePolicy)
        self.drag_and_drop_box.setMinimumSize(QtCore.QSize(450, 110))
        self.drag_and_drop_box.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.drag_and_drop_box.setFont(font)
        self.drag_and_drop_box.viewport().setProperty("cursor", QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.drag_and_drop_box.setStyleSheet("QListWidget {\n"
"    background-image: url(:/background/images/background/drag_drop.png);\n"
"    background-repeat: no-repeat;\n"
"    background-position: center;\n"
"    color: #dedede;\n"
"    border: 1px solid #dedede;\n"
"    padding: 5px;\n"
"    border-radius: 15px;\n"
"}\n"
"\n"
"QListWidget::Item {\n"
"    background: #002A44;\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QListWidget::Item:selected {\n"
"    background: #3C5F85;\n"
"}\n"
"\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 14px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
"\n"
" QScrollBar::handle:vertical {    \n"
"    background: rgb(85, 170, 255);\n"
"    min-height: 25px;\n"
"    border-radius: 7px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 7px;\n"
"    border-bottom-right-radius: 7px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
"\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"")
        self.drag_and_drop_box.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.drag_and_drop_box.setFrameShadow(QtWidgets.QFrame.Plain)
        self.drag_and_drop_box.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.drag_and_drop_box.setDragDropMode(QtWidgets.QAbstractItemView.DropOnly)
        self.drag_and_drop_box.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.drag_and_drop_box.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.drag_and_drop_box.setObjectName("drag_and_drop_box")
        item = QtWidgets.QListWidgetItem()
        self.drag_and_drop_box.addItem(item)
        item = QtWidgets.QListWidgetItem()
        self.drag_and_drop_box.addItem(item)
        self.verticalLayout_12.addWidget(self.drag_and_drop_box, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.verticalLayout_13.addLayout(self.verticalLayout_12)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setSpacing(5)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem)
        self.btn_remove_picture = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_remove_picture.sizePolicy().hasHeightForWidth())
        self.btn_remove_picture.setSizePolicy(sizePolicy)
        self.btn_remove_picture.setMinimumSize(QtCore.QSize(110, 30))
        self.btn_remove_picture.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_remove_picture.setFont(font)
        self.btn_remove_picture.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_remove_picture.setStyleSheet("QPushButton {\n"
"    color: #dedede;\n"
"    background: #002A44;\n"
"    border: 2px solid #dedede;\n"
"    border-radius: 15px;\n"
"    padding: 1px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #003c5f;\n"
"    border-color: #F38533;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #F38533;\n"
"}")
        self.btn_remove_picture.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.Cameroon))
        self.btn_remove_picture.setObjectName("btn_remove_picture")
        self.horizontalLayout_14.addWidget(self.btn_remove_picture, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.btn_select_pictures = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_select_pictures.sizePolicy().hasHeightForWidth())
        self.btn_select_pictures.setSizePolicy(sizePolicy)
        self.btn_select_pictures.setMinimumSize(QtCore.QSize(110, 30))
        self.btn_select_pictures.setMaximumSize(QtCore.QSize(110, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.btn_select_pictures.setFont(font)
        self.btn_select_pictures.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_select_pictures.setStyleSheet("QPushButton {\n"
"    color: #dedede;\n"
"    background: #002A44;\n"
"    border: 2px solid #dedede;\n"
"    border-radius: 15px;\n"
"    padding: 1px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #003c5f;\n"
"    border-color: #F38533;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #F38533;\n"
"}")
        self.btn_select_pictures.setObjectName("btn_select_pictures")
        self.horizontalLayout_14.addWidget(self.btn_select_pictures, 0, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem1)
        self.verticalLayout_13.addLayout(self.horizontalLayout_14)
        self.horizontalLayout.addLayout(self.verticalLayout_13)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(180, 400, 571, 37))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btn_update_student = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_update_student.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_update_student.sizePolicy().hasHeightForWidth())
        self.btn_update_student.setSizePolicy(sizePolicy)
        self.btn_update_student.setMinimumSize(QtCore.QSize(120, 0))
        self.btn_update_student.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_update_student.setFont(font)
        self.btn_update_student.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_update_student.setStyleSheet("QPushButton {\n"
"    color: #dedede;\n"
"    background: #002A44;\n"
"    border: 2px solid #dedede;\n"
"    border-radius: 15px;\n"
"    padding: 1px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #003c5f;\n"
"    border-color: #F38533;\n"
"}\n"
"\n"
"QPushButton:!enabled\n"
"{\n"
"     background-color: #004c5f;\n"
"        border-right: 5px solid #dedede;\n"
"        border-left: 5px solid #dedede;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #F38533;\n"
"}")
        self.btn_update_student.setObjectName("btn_update_student")
        self.horizontalLayout_2.addWidget(self.btn_update_student)
        self.btn_cancel_update_student = QtWidgets.QPushButton(self.layoutWidget1)
        self.btn_cancel_update_student.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_cancel_update_student.sizePolicy().hasHeightForWidth())
        self.btn_cancel_update_student.setSizePolicy(sizePolicy)
        self.btn_cancel_update_student.setMinimumSize(QtCore.QSize(120, 0))
        self.btn_cancel_update_student.setMaximumSize(QtCore.QSize(300, 35))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cancel_update_student.setFont(font)
        self.btn_cancel_update_student.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.btn_cancel_update_student.setStyleSheet("QPushButton {\n"
"    color: #dedede;\n"
"    background: rgb(179, 32, 27);\n"
"    border: 2px solid #dedede;\n"
"    border-radius: 15px;\n"
"    padding: 1px 10px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    border-color: #F38533;\n"
"}\n"
"\n"
"\n"
"QPushButton:!enabled\n"
"{\n"
"     background-color: #A03c5f;\n"
"        border-right: 5px solid #dedede;\n"
"        border-left: 5px solid #dedede;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #F38533;\n"
"}")
        self.btn_cancel_update_student.setObjectName("btn_cancel_update_student")
        self.horizontalLayout_2.addWidget(self.btn_cancel_update_student)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Update Student"))
        self.student_name_label_2.setText(_translate("Dialog", "Update student informations"))
        self.student_name_label.setText(_translate("Dialog", "Name"))
        self.student_name_lineEdit.setPlaceholderText(_translate("Dialog", "Name"))
        self.student_surname_label.setText(_translate("Dialog", "Surname"))
        self.student_surname_lineEdit.setPlaceholderText(_translate("Dialog", "Surname"))
        self.student_register_number_label.setText(_translate("Dialog", "Register Number"))
        self.student_register_number_lineEdit.setPlaceholderText(_translate("Dialog", "Register Number"))
        self.student_level_label.setText(_translate("Dialog", "Level"))
        self.student_discipline_label.setText(_translate("Dialog", "Discipline"))
        self.student_discipline_comboBox.setPlaceholderText(_translate("Dialog", "-- Discipline --"))
        self.student_discipline_comboBox.setItemText(0, _translate("Dialog", "GIT"))
        self.student_discipline_comboBox.setItemText(1, _translate("Dialog", "TTIC"))
        self.student_discipline_comboBox.setItemText(2, _translate("Dialog", "GP"))
        self.student_discipline_comboBox.setItemText(3, _translate("Dialog", "GAM"))
        self.student_discipline_comboBox.setItemText(4, _translate("Dialog", "ROI"))
        self.student_discipline_comboBox.setItemText(5, _translate("Dialog", "GESI"))
        self.student_discipline_comboBox.setItemText(6, _translate("Dialog", "GC"))
        self.student_discipline_comboBox.setItemText(7, _translate("Dialog", "TAU"))
        self.student_axe_label.setText(_translate("Dialog", "Axe"))
        self.student_axe_comboBox.setPlaceholderText(_translate("Dialog", "-- Axe --"))
        self.label_drag_and_drop.setText(_translate("Dialog", "Drag and Drop the pictures here ☺"))
        __sortingEnabled = self.drag_and_drop_box.isSortingEnabled()
        self.drag_and_drop_box.setSortingEnabled(False)
        item = self.drag_and_drop_box.item(0)
        item.setText(_translate("Dialog", "c:/jordan/pictures/jordan.jpg"))
        item = self.drag_and_drop_box.item(1)
        item.setText(_translate("Dialog", "c:/jordan/pictures/jordan.jpg"))
        self.drag_and_drop_box.setSortingEnabled(__sortingEnabled)
        self.btn_remove_picture.setText(_translate("Dialog", "Remove"))
        self.btn_select_pictures.setText(_translate("Dialog", "Choose"))
        self.btn_update_student.setText(_translate("Dialog", "Update"))
        self.btn_cancel_update_student.setText(_translate("Dialog", "Cancel"))
